version: "3.9"
services:
  caddy:
    #image: livekit/caddyl4
    build:
      context: ./
      dockerfile: ./caddyl4_Dockerfile
    #command: run --config /etc/caddy.yaml --adapter yaml
    command: run --config /etc/caddy.json
    restart: unless-stopped
    network_mode: "host"
    volumes:
      #- ./caddy.yaml:/etc/caddy.yaml
      - ./caddy.json:/etc/caddy.json
      - ./caddy_data:/data
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
  redis:
    image: redis:6-alpine
    command: redis-server /etc/redis.conf
    network_mode: "host"
    volumes:
      - ./redis.conf:/etc/redis.conf